monitor = HDMI-A-1, 1920x0, 0x0, 1

exec-once = hyprctl setcursor Bibata-Modern-Classic 30
exec-once = fcitx5
exec-once = hyprpaper
exec-once = qs

$mod = SUPER

misc {
  disable_hyprland_logo = true
}

xwayland {
  force_zero_scaling = true
}

general {
  allow_tearing = false

  gaps_in = 10
  gaps_out = 20

  layout = dwindle

  col.inactive_border = rgba(414559ff)
  col.active_border = rgba(8caaeeff)

  border_size = 0
  resize_on_border = false
}

decoration {
  blur {
    enabled = true
    passes = 2
    size = 1
    vibrancy = 0.520800
  }

  active_opacity = 1
  inactive_opacity = 1
  rounding = 10
}

device {
  name = epic-mouse-v1
  sensitivity = -0.500000
}

animations {
  enabled = true

  bezier = easeOutQuint, 0.23, 1, 0.32, 1
  bezier = linear, 0, 0, 1, 1
  bezier = smoothElastic, 1, -0.3, 0.3, 1.2

  animation = windows, 1, 4, easeOutQuint
  animation = windowsIn, 1, 4, easeOutQuint, slide
  animation = windowsOut, 1, 4, easeOutQuint, slide
  animation = layersIn, 1, 4, easeOutQuint, gnomed
  animation = layersOut, 1, 1.5, linear, gnomed
  animation = workspacesIn, 1, 4, smoothElastic, slide
  animation = workspacesOut, 1, 4, smoothElastic, slide
}

dwindle {
  preserve_split = true
  pseudotile = false
}

input {
  touchpad {
    natural_scroll = false
  }

  follow_mouse = 1
  kb_layout = br
  kb_variant = abnt2
  sensitivity = 0
}

master {
  new_status = master
}

bind = $mod, Q, killactive
bind = $mod, A, exec, qs ipc call controlcenter toggle
bind = $mod, D, exec, qs ipc call desktopstyle toggle
bind = $mod, Space, exec, qs ipc call applauncher toggle
bind = $mod, P, pseudo
bind = $mod, F, togglefloating
bind = $mod, E, exec, zedit
bind = $mod, return, exec, ghostty

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

bind = $mod SHIFT, H, swapwindow, l
bind = $mod SHIFT, J, swapwindow, d
bind = $mod SHIFT, K, swapwindow, u
bind = $mod SHIFT, L, swapwindow, r

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

bind = $mod, mouse_down, workspace, e-1
bind = $mod, mouse_up, workspace, e+1

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

binde = ALT, L, resizeactive, -20 0
binde = ALT, J, resizeactive, 0 20
binde = ALT, K, resizeactive, 0 -20
binde = ALT, H, resizeactive, 20 0
