exec-once = fcitx5 -d

bind = Super, N, exec, caelestia shell drawers toggle sidebar
bind = Super, H, exec, caelestia shell mpris playPause
bind = Super, T, exec, caelestia shell controlCenter open
bind = Super, A, exec, caelestia shell drawers toggle dashboard