exec-once = fcitx5 -d

bind = Super, N, exec, caelestia shell drawers toggle sidebar
bind = Super, T, exec, caelestia shell controlCenter open
bind = Super, A, exec, caelestia shell drawers toggle dashboard

bind = , KP_Left, exec, caelestia shell mpris previous
bind = , KP_Begin, exec, caelestia shell mpris playPause
bind = , KP_Right, exec, caelestia shell mpris next